JioCloud/cinder

cinder/db/sqlalchemy/migrate_repo/versions/042_add_per_volume_quota.py, cinder/exception.py, cinder/quota.py, cinder/tests/api/contrib/test_quotas.py, cinder/tests/api/contrib/test_quotas_classes.py, cinder/tests/test_quota.py, cinder/volume/flows/api/create_volume.py
Set max volume size limit for the tenant
There is a need to limit maximum size of a volume to levels
that the storage infrastructure can handle.
Setting a maximum limit on size of a volume also prevents
a tenant from creating large volumes that have not been tested
and certified to satisfy SLA objectives.
=> set_volume_size_limit

cinder/policy.py, etc/cinder/api-paste.ini, etc/cinder/mapping.json
Each service will now communicate to IAM, the resource ID and action ID as two additional parameters in token validation API (new Authorize API). IAM will verify based on its policies and respond to the service with all the details that token API did, with an additional “Yes” or “No” response- whether a user is allowed to perform the action on that specific resource.
To cater to these new IAM changes, a new middleware is added; it communicates to IAM, the action and the associated resource corresponding to each API.
https://github.com/vivekdhayaal/jiocloud_auth_middleware
Note that this middleware is added for cinder-v2 API only. Since we don't support v1 we should disable v1 in prod through config options.
* cinder/policy.py
+ Disabled policy check at cinder
* etc/cinder/api-paste.ini
+ …
=> SBS-IAM-INTEGRATION

cinder/api/contrib/backups.py
We support backup even if volumes are attached as default
behavior. Additionaly, send the force arg to create in
the right order
=> Backup: Use force option as default

cinder/quota.py
gigabyte = 120000G
volumes = 120
backups = 240
backup_gigabyte = 28800000
per_volume_size_limit = 1000G
=> Set default quota limits

cinder/quota.py
max volume size: 1024GB
max gb for backups: 1024 * 240 (240 snaps is per volume)
=> Limits: update to default limits

cinder/backup/drivers/sbs.py, cinder/db/sqlalchemy/migrate_repo/versions/044_add_version_to_backups.py, cinder/db/sqlalchemy/models.py
Continuation of JBS-23
We want to make sure the snapshots/backups stored are identified with a version, so that in the
future if we deviate in the way we take/restore and backup snapshots, we should have the ability
to atleast restore/delete older version backups
As for creation, it is always good to support only newer version.
Also, if backups exist for a volume, make sure different versions are not supported on the same
=> Support versioning of backup drivers

cinder/backup/drivers/sbs.py
If the src snapshot was identified during list, but not found during
actually deletion, do not error out. Volume deletion, which is a
independent operation will also remove src snapshot if any
=> JBS-85: If src snapshot is not found, do not error out while deleting

cinder/backup/api.py, cinder/backup/rpcapi.py
Removed the coupling between volume and backup services.
Now, backup requests will be sent to one of the available backup services
in round robin fashion
Closes-Bug: #JBS-97
=> cinder backup HA

cinder/volume/rpcapi.py
Removed the coupling between volume and and its host.
Now, volume requests will be sent to one of available volume service
hosts in round robin fashion
Closes-Bug: #JBS-105
=> cinder volume HA

cinder/volume/drivers/rbd.py
If a volume is being deleted, it tries to clear the
snapshots by fetching a list from ceph cluster. A parallel snapshot
delete might also remove the same. Make sure we do
not error out if the snapshot was removed from the
db
=> Handle race between snap delete and volume delete

cinder/scheduler/host_manager.py, cinder/tests/scheduler/test_host_manager.py
We run cinder-volume service in active passive mode. There were "volume
service is down" warning messages in cinder-volume logs about the
passive volume service. This led to misinterpretation that there were
problems with the volume service.
So, this patch decreased the log level of this message to 'DEBUG'.
We should switch back once we have cinder-volume service running in
active-active mode as this message is a useful health check indicator.
Closes-Bug: #JBS-108
=> "volume service is down" warnings misinterpreted

cinder/backup/drivers/sbs.py
This fails when non-admin triggers snapshot delete
=> JBS-109: remove db entry for snapshot delete in elevated context

cinder/volume/drivers/rbd.py
Move RBD calls to a separate threads
RBD is a python binding for librados which isn't patched by eventlet.
Making long-running tasks like removing big (~100GB, ~1TB) volumes
blocks eventlet loop and all cinder-volume service hangs
until it finished when rados_connect_timeout is disabled. It makes
cinder-volume services unavailable for a while.
This patch moves all rados calls to a separate python thread which
doesn't block eventlet loop.
Change-Id: Ibaf43858d60e1320c339f2523b5c09c7f7c7f91e
Closes-Bug: #1401335
Conflicts:
cinder/volume/drivers/rbd.py
=> JBS-125: Cinder-Volume is serialized at RBD side.

cinder/api/metricutil.py, cinder/api/openstack/wsgi.py, cinder/api/v2/volumes.py, cinder/backup/drivers/sbs.py, cinder/volume/api.py, requirements.txt
Tested with the new changes
vagrant@cinder:~/workspace/cinder$ time cinder list
+--------------------------------------+----------------+-----------------------------------------------------+------+-------------+----------+-------------+
|                  ID                  |     Status     |                         Name                        | Size | Volume Type | Bootable | Attached to |
+--------------------------------------+----------------+-----------------------------------------------------+------+-------------+----------+-------------+
| 7518e108-a3e8-443f-a367-bff4034a2ec5 |   available    |                         None                        |  1   |     None    |  false   |             |
| 75cd6044-1bbc-41b8-b7cc-ba8a40992521 |   available    |                         None …
=> Merge Monitoring Changes of cinder to JioCloud Cinder branch

cinder/volume/drivers/rbd.py
Currently we are using tpool size as default 20.
rbd_tpool_size option can be now set through cinder.conf
=> JBS-156 volume tpool: Make thread pool size configurable

cinder/db/sqlalchemy/api.py, cinder/db/sqlalchemy/models.py
Updated CRUD operations to store timestamps in IST
Test cases verified:
* Verified that timestamps are in IST in below CLI operations,
"create, show, delete, backup-create, backup-show, backup-delete"
Note:
* This is not a cinder wide change but just limited to volumes and backups
* Cinder is not timezone aware
Closes-Bug: #JBS-157
=> Volume Creaton time is GMT and not IST

cinder/backup/api.py, cinder/volume/api.py, cinder/volume/flows/api/create_volume.py
Tested
ubuntu@compute2:/usr/lib/python2.7/dist-packages$ curl -X GET -H "Accept-Encoding: identity" -H "User-Agent: curl/7.35.0" -H "Content-Type: application/json" "http://10.140.12.215:8788/services/Cloud/?TokenId=ca4b8ca83a1b482e90046ad4222a3db1&ProjectId=82deb70d37c14d44a25b518e829802ca&UserId=b5c7d23859154bc182bab1f303dc0a20&RequestId=req-baa52567-8cb8-4dc4-849c-08e738a4591f&Action=CreateVolume&SnapshotId=48fa281f-4ef2-42db-8e18-d26ef9509a2c"
<CreateVolumeResponse xmlns="http://compute.jiocloudservices.com/doc/2016-03-01/">
<requestId>req-baa52567-8cb8-4dc4-849c-08e738a4591f</requestId>
<status>creating</status>
<volumeId>8ed739db-d609-48a5-894e-136dfbdab940</volumeId>
<attachmentSet/>
<snapshotId>48fa281f-4ef2-42db-8e18-d26ef9509a2c</snapshotId> …
=> Storing Volume Id in Snapshot Database

cinder/volume/drivers/rbd.py
If a volume has a backup in creation state, we error out delete
with a volume busy error. By not catching the exception, the
rbd image would not be closed, leading to rbd driver to crash/hang.
=> JBS-183: Close rbd_image if volume has backups in creation state

cinder/backup/drivers/sbs.py
We update 1st snapshot created_at time, so that it is higher
than the base snapshot.
With changes in timestamp to IST, the 1st snapshot was getting
UTC, which would be behind IST, leading to failure in deleting
that snapshot.
And further snapshots would be rejected on the volume, as the latest
snapshot would be stuck in deletion.
=> JBS-192: Update 1st snapshot timestamp to IST

cinder/volume/drivers/rbd.py
It currently uses same thread_pool size as tpool
=> JBS-217: Use seperate dpool for RBD remove operation

cinder/db/sqlalchemy/migrate_repo/versions/047_change_actual_size_to_bigint.py, cinder/db/sqlalchemy/models.py
Reverted change in 046_add_actual_size_to_backups.py from earlier fix
Update/alter is introduced in 047_change_actual_size_to_bigint.py
Signed-off-by: shishir gowda <shishir@shishirs-MacBook-Pro.local>
=> JBS-389: change actual_size to BigInteger
