JioCloud/cinder

cinder/api/contrib/backups.py
cinder/backup/api.py

Closes-bug: https://bugs.launchpad.net/jio/+bug/1451959

Backups: add a force flag

---

cinder/backup/api.py

Build Fix: Move default args to end of list of args

---

etc/cinder/mapping.json

Addressed review comments:
* Added tenant_id as resourceType for backup create operation
* Added tenant_id as resourceType for all list<resource> operations
https://blueprints.launchpad.net/jio/+spec/sbs-iam-integration
Implements bp sbs-iam-integration

SBS-IAM-INTEGRATION

---

cinder/backup/api.py
cinder/backup/manager.py
cinder/backup/rpcapi.py

Save the original state before moving it to "backing-up"
and pass it to the create_backup call to be used to resetting
bug: JBS-54

JBS-54: Reset volume correct volume status

---

cinder/backup/api.py
cinder/backup/drivers/ceph.py
cinder/backup/drivers/sbs.py
cinder/backup/manager.py
cinder/db/sqlalchemy/migrate_repo/versions/043_add_deleted_column_to_backups.py
cinder/db/sqlalchemy/migrate_repo/versions/043_add_time_stamp_column_to_backups.py
cinder/db/sqlalchemy/models.py
cinder/volume/drivers/rbd.py

Backup to s3

---

cinder/backup/drivers/sbs.py

Addressed few review comments and added exception handling for failures

JBS-23: review comment fixes

---

cinder/backup/drivers/sbs.py

JBS-23: added host to upload to dss

support multipart upload

---

cinder/backup/drivers/sbs.py

Additionally, if last snapshot is deleted, delete base too
Also check for base and from_snapshot status
JBS-85

Snapshot: Base image should be unique and not volume_id

---

debian/control

Added dependency for boto and filechunkio

build dependencies

---

cinder/readerwriterlockutils.py
cinder/volume/manager.py

Limitation:
-------------
This will not work if we have multiple cinder-volume processes on same / different nodes

JBS-87: CreateVolume from snapshot is not concurrent

---

cinder/api/v2/views/volumes.py
cinder/api/v2/volumes.py
cinder/db/sqlalchemy/migrate_repo/versions/042_add_misc_field_to_volumes.py
cinder/db/sqlalchemy/models.py
cinder/volume/api.py
cinder/volume/flows/api/create_volume.py

Signed-off-by: Prashant Upadhyay <prashant.upadhyay709070@gmail.com>
NOT TO BE MERGED !!

temp branch; avoid snapshot ID in cinder show for the volume when created using cache.

---

cinder/backup/drivers/sbs.py

JBS-85: If getting Object store bucket handle fails, error out

---

cinder/volume/drivers/rbd.py

JBS-54: pass context for delete_volume in rbd driver

---

cinder/backup/drivers/sbs.py

Fix error/msg to pass to exceptions

---

cinder/volume/manager.py

JBS-105: Donot check host info for volume deletion

---

cinder/constants.py

Follow up to fc28a8ae9bcae4798fd62e810f2b389c99a41c22.
Added file missed in above commit.
Closes-Bug: #JBS-105

cinder volume HA

---

cinder/volume/drivers/rbd.py

ENV var should be a string

---

cinder/api/openstack/wsgi.py

Checked with raising an exception without a code
Raised in favor of comments in 
https://github.com/JioCloud/cinder/pull/62
Made some other commits in that branch which are difficult to  remove
2016-04-01 14:05:50.465 17627 ERROR cinder.api.openstack.wsgi [req-2ff845ac-dcb7-4ffa-a0ac-5b2e6b4c99f2 b5c7d23859154bc182bab1f303dc0a20 82deb70d37c14d44a25b518e829802ca - - -] Exception in cinderAPI: New Exception
2016-04-01 14:05:50.465 17627 TRACE cinder.api.openstack.wsgi Traceback (most recent call last):
2016-04-01 14:05:50.465 17627 TRACE cinder.api.openstack.wsgi   File "/usr/lib/python2.7/dist-packages/cinder/api/openstack/wsgi.py", line 988, in __call__
2016-04-01 14:05:50.465 17627 TRACE cinder.api.openstack.wsgi     raise exception
2016-04-01 14:05:50.465 17627 TRACE …

Addresing Vivek's comments in fixing service logs error codes

---

cinder/backup/api.py

Currently, we do not check if a snapshot is in creating state, and
accept a new snapshot create request on the same volume. This happens
as we reset volume status from backing up after src snapshot is done.
New snapshot entry gets created, but snapshot fails if previous snap
is still in progress, as entry in DSS would not be available.
The check is to make sure parent snapshot is in "available" state
in the api layer itself.

JBS-190: Check if parent snapshot is available before creating new

---

cinder/backup/drivers/sbs.py
cinder/db/sqlalchemy/migrate_repo/versions/046_add_actual_size_to_backups.py
cinder/db/sqlalchemy/models.py

Also, verify if downloaded snapshot size is < than expected
and error out.
If no size is saved, then we do not verify while downloading

JBS-240: Save actual snapshot size while uploading to DSS

---

cinder/db/sqlalchemy/migrate_repo/versions/046_add_actual_size_to_backups.py

Deployment into devtest for JBS-254 failed during migration.
Added the import missed in JBS-240.
Closes-Bug: #JBS-254

Fix ImportError during migration for JBS-240

---

cinder/api/metricutil.py
cinder/api/middleware/fault.py
cinder/api/openstack/wsgi.py
cinder/volume/drivers/rbd.py
cinder/volume/flows/manager/create_volume.py
cinder/volume/manager.py

Did volume create and delete tests and tested api, scheduler and volume metrics.
===========================================
StartTime=1462126594.28
EndTime=2016-05-01 18:16:34
Time=448 ms
OperationName=cinder-volume-create
HostName=ip-10-0-0-4
PID=3184
TenantId=00000000000000000000631677221232
RequestId=req-8c29dd05-c91c-4205-9042-6aa85cfb09fb
ProgramName=CinderVolume
MarketplaceId=IDC1
Timing=mysql-db-volume-get_time=39 ms,rbd-create-volume_time=268 ms,ExtractVolumeSpecTask_execute-time=0 ms,OnFailureRescheduleTask_execute-time=0 ms,CreateVolumeOnFinishTask_execute-time=47 ms,NotifyVolumeActionTask_execute-time=0 ms,CreatingToAvailable=676 ms,CreateVolumeFromSpecTask_execute-time=269 ms,ExtractVolumeRefTask_execute-time=40 ms,
Counters=Success=1,OnFailureRescheduleTask_execute-occurence= …

[JBS-328]  Add more metrics for cinder layer

---

cinder/db/api.py
cinder/db/sqlalchemy/api.py
cinder/objects/base.py
cinder/volume/api.py

Still need to test this out. So, don't merge it.

Moved the attach, detach, initiate and terminate connection requests from volume layer to api layer 

---

cinder/db/sqlalchemy/migrate_repo/versions/046_add_actual_size_to_backups.py
cinder/db/sqlalchemy/models.py

Signed-off-by: shishir gowda <shishir@shishirs-MacBook-Pro.local>

JBS-389: Set actual_size width to 32 from default int option of 11

---

cinder/backup/drivers/sbs.py

If the dst volume size > snapshot size (src volume size from which
snap was taken), the volume gets shrunk to the src size after a
volume restore (import-diff). We need to explicitly call image
resize if dst volume size is > than snapshot size.

JBS-436: Support resizing of volumes after a restore of snapshot
